#!/usr/bin/env bash

# System Environment Variables

PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:$PATH

# Shell Options
# #############

shopt -s nocaseglob

shopt -s histappend

# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit'

# Whenever displaying the prompt, write the previous line to disk
export PROMPT_COMMAND="history -a"

GREP_OPTIONS='--color=auto'
GREP_COLOR='1;32'
alias ls='ls -FG'

export HISTCONTROL="ignoredups"
export HISTFILESIZE=500000
export HISTSIZE=500000

SMILEY="👊"
FROWNY="💩"

function goWell () {
  if [[ $? = 0 ]];
  then
    echo $SMILEY;
  else
    echo $FROWNY;
  fi
}

if [[ ! $PROMPT_COMMAND =~ store_exit_status ]]; then
  export PROMPT_COMMAND="store_exit_status && ${PROMPT_COMMAND:-:}"
fi

store_exit_status() {
  LAST_EXIT_STATUS=$?
}

# Emits exit status of last command if error condition returned.
show_exit_status() {
  if [ "x${LAST_EXIT_STATUS}" != "x0" ]; then
    echo ${FROWNY}
  else
    echo ${SMILEY}
  fi
}

if [[ $(type -t prompt_animal) != function ]]
then
  prompt_animal() {
    # go run ~/Dropbox/randomline/randomline.go ~/.prompt_animals 2>&1
    gsort -R < ~/.prompt_animals | head -1
  }
fi

export PS1='\n\! @ \D{%m-%d %H:%M:%S}: $(show_exit_status)\n\[\u@$(hostname)\]:\w \n$(prompt_animal)  '
export PS2=">\$ "
export PS3="#? "
export PS4="+$ "

# Functions

for f in ~/bin/functions/*.bash
do
  if [[ -f $f ]]
  then
    . "$f"
  fi
done

# Aliases

for f in ~/.aliases/*.bash;
do
  if [[ -f $f ]]
  then
    . "$f"
  fi
done

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Navigation -------------------------------------------------------
alias ..='cd ..'
alias ...='cd ../..'

alias df='df -h'
alias ag='ag --pager "less -R"'

# Editors ----------------------------------------------------------
export EDITOR='vim'

if type emacs > /dev/null 2>&1
then
    export EDITOR='emacs'
fi
