#!/usr/bin/env bash

export PATH=$HOME/bin:$PATH:$HOME/.rvm/bin

# source the system wide bashrc if it exists
if [ -f /etc/bashrc ] ; then
  source /etc/bashrc
fi

source ~/.bashrc

# if [ -f $(brew --prefix)/etc/bash_completion ]
# then
#   . $(brew --prefix)/etc/bash_completion
# fi

if [[ -f ~/.$(hostname).bash ]]
then
  . ~/."$(hostname)".bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
